### PR TITLE
add __all__ to python files that misses it

### PR DESCRIPTION
**Pull request by xwu64**
use tool (https://github.com/xwu64/python-auto-all) to generate`__all__` for python files. This tool go through all python files and ignores file, class and function with prefix "_". 
In this commit, I manually remove `__all__` for test files.

### CODE REVIEW

**Comment by xwu64** [comment]
I don't know the reason of error in line/pre-commit test

**Comment by Trim21** [comment]
因为你只跑了这个工具，没format

**Comment by Trim21** [comment]
而且感觉 router handler 没必要放到`__all__`里，真正用于其他文件导入的`router`又没被包括

**Comment by Trim21** [comment]
https://github.com/bangumi/server#%E4%BB%A3%E7%A0%81%E9%A3%8E%E6%A0%BC

**Pull request closed without merging**
